name: Docker Image CI
# EVENTO
on:
  push:
    branches: [ "master" ]
    tags:        
      - '*'

jobs:
  tests: 
    runs-on: ubuntu-24.04
    steps:
    - name: Hacer checkout    
      uses: actions/checkout@v4
      
    - name: Instalar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Instalar dependencias
      run: composer install 

    - name: Ejecutar los tests
      run: vendor/bin/phpunit --testdox tests
  
  build:
    needs: tests
# IMAGEN
    runs-on: ubuntu-latest
    steps:
    # Acción que vine con github, descarga todo lo que hay en el repo y lo mete en la imagen.
    - name: Hacer checkout
      uses: actions/checkout@v4

    - uses: little-core-labs/get-git-tag@v3.0.1
      id: tagName

    # Login con el Docker Login del Marketplace
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_USER }}/calculadoradocker:$GIT_TAG_NAME
